### ISSUE TITLE
ODataReader should gracefully handle unexpected Annotations

### ISSUE THREAD

**Issue by joshgav** [Microsoft/Vipr#62]
For CSDL files with unexpected Annotations, the Reader fails with an error as follows (endpoint changed for privacy). It would be better if it ignored such annotations and logged that it had to do so.

```
>> vipr.exe https://my.end.point/$metadata

Downloading metadata from https://my.end.point/$metadata
Generating Client Library to C:\cygwin64\home\joshgav\git\vipr-t4templatewriter\src\T4TemplateWriter\bin\debug\output

Unhandled Exception: System.TypeLoadException: Could not load type 'Vipr.Core.CodeModel.Vocabularies.Capabilities.NavigationRestrictionsType' from assembly 'Vipr.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
   at ODataReader.v4.ODataVocabularyReader.FetchNewInstanceOfAnnotationComplexType(IEdmType type) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Readers\ODataReader.v4\ODataVocabularyReader.cs:line 385
   at ODataReader.v4.ODataVocabularyReader.MapToClr(IEdmTypeReference valueType, IEdmExpression valueExpression) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Readers\ODataReader.v4\ODataVocabularyReader.cs:line139
   at ODataReader.v4.ODataVocabularyReader.<GetOdcmAnnotations>d__2.MoveNext() in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Readers\ODataReader.v4\ODataVocabularyReader.cs:line 115
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ODataReader.v4.OdcmReader.ReaderDaemon.AddVocabularyAnnotations(OdcmObject odcmObject, IEdmVocabularyAnnotatable annotatableEdmEntity) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Readers\ODataReader.v4\OdcmReader.cs:line 117
   at ODataReader.v4.OdcmReader.ReaderDaemon.WriteNamespaceDeep(IEdmModel edmModel, String namespace) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Readers\ODataReader.v4\OdcmReader.cs:line 286
   at ODataReader.v4.OdcmReader.ReaderDaemon.WriteNamespaces() in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Readers\ODataReader.v4\OdcmReader.cs:line 130
   at ODataReader.v4.OdcmReader.ReaderDaemon.GenerateOdcmModel(TextFileCollection serviceMetadata) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Readers\ODataReader.v4\OdcmReader.cs:line 102
   at ODataReader.v4.OdcmReader.GenerateOdcmModel(TextFileCollection serviceMetadata) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Readers\ODataReader.v4\OdcmReader.cs:line 61
   at Vipr.Bootstrapper.MetadataToClientSource(String edmxString) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Core\Vipr\Bootstrapper.cs:line 112
   at Vipr.Bootstrapper.MetadataToClientSource(String edmxString, String outputDirectoryPath) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Core\Vipr\Bootstrapper.cs:line 107
   at Vipr.Bootstrapper.Start(String[] args) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Core\Vipr\Bootstrapper.cs:line 45
   at Vipr.Program.Main(String[] args) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Core\Vipr\Program.cs:line 19
```

**Comment by mattgeim** [comment]
Same as issue 84.  closing.
