### ISSUE TITLE
Support basic auth for grabbing metadata from URL

### ISSUE THREAD

**Issue by joshgav** [Microsoft/Vipr#64]
It's helpful to point the Vipr CLI at a URL to download metadata on the fly. However, many metadata endpoints are protected by auth. Could we add support for basic auth or OAuth to get metadata?

Current error looks like this:
```
Unhandled Exception: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Vipr.MetadataResolver.LoadEdmxFromWeb(String uri) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Core\Vipr\MetadataResolver.cs:line 38
   at Vipr.MetadataResolver.GetMetadata(String metadataPath) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Core\Vipr\MetadataResolver.cs:line 18
   at Vipr.Bootstrapper.Start(String[] args) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Core\Vipr\Bootstrapper.cs:line 41
   at Vipr.Program.Main(String[] args) in c:\cygwin64\home\joshgav\git\vipr-t4templatewriter\submodules\vipr\src\Core\Vipr\Program.cs:line 19
```

**Comment by mattgeim** [comment]
There isn't a large need for this, don't see it being prioritized over other issues.  Re-open if needed.
